services:
  - type: web
    name: n8n-dashboard
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: N8N_RUNNERS_ENABLED
        value: "true"
      - key: N8N_BLOCK_ENV_ACCESS_IN_NODE
        value: "false"
      - key: N8N_GIT_NODE_DISABLE_BARE_REPOS
        value: "true"
      - key: N8N_PORT
        value: "5678"
    dockerfilePath: ./Dockerfile
